Release 0.2.0
max-underthesun/react-blog pull request #2
Opened 2016-12-26 13:18 UTC by max-underthesun

2016-12-26 19:07 UTC, index01d requested changes

2016-12-26 19:07 UTC, index01d commented on src/BlogList.js
> +  props_formatted() {
Название методов лучше делать camelCase'ом. Форматирующий метод лучше вынести из компонента (он же может использоваться не только здесь).

2016-12-26 19:07 UTC, index01d commented on src/BlogList.js
> +    meta: { createdAt: moment(), updatedAt: new Date(), count: 7 }
интересное решение, мб лучше задать даты в виде строки с ISO?

2016-12-29 10:20 UTC, max-underthesun commented on src/BlogList.js
> +    meta: { createdAt: moment(), updatedAt: new Date(), count: 7 }
ага... )) сделал

2016-12-29 10:20 UTC, max-underthesun commented on src/BlogList.js
> +  props_formatted() {
- название случайно "сорвалось" - руби-привычка однако
 - форматирование вынес во внешние функции

2017-01-09 15:09 UTC, index01d requested changes
Лучше с помощью уже существующих определений поточнее определить типы в общем компоненте.

2017-01-09 15:09 UTC, index01d commented on src/BlogList.js
> +  image: PropTypes.object.isRequired,
С помощью PropTypes.shape можно сослаться на определение типа с Image.propTypes

2017-01-09 15:09 UTC, index01d commented on src/BlogList.js
> +  meta: PropTypes.object.isRequired
то же самое.

2017-01-09 17:09 UTC, index01d approved these changes

2017-01-10 07:05 UTC, merged